version: '3.8'

services:
  todoui3:
    build: .
    container_name: todoui3
    restart: always
    ports:
      - "3030:3030"
    networks:
      - mynetwork3

networks:
  mynetwork3:
    driver: bridge
