version: '3.8'

services:
  todoui3:
    build: .
    container_name: todoui3
    restart: always
    ports:
      - "3030:3030" # Порт приложения
      - "5005:5005"  # Порт для отладки
    networks:
      - mynetwork3

networks:
  mynetwork3:
    driver: bridge
